apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nitro2-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nito2
    spec:
      containers:
      - name: nitro2
        image: karthi102/nitro:37
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
